name: Rust Code Checks
run-name: ${{ github.actor }} Push Code
on: [pull_request]

jobs:
  format:
    name: Format Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libsoup3.0-dev
          cargo clippy -- -D warnings

